linters:
  enable:
  - bodyclose
  - dogsled
  - dupl
  - errcheck
  - exportloopref
  - gochecknoglobals
  - gochecknoinits
  - gochecknoinits
  - goconst
  - gocritic
  - gocyclo
  - gofmt
  - goimports
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - ineffassign
  - misspell
  - nakedret
  - revive
  - rowserrcheck
  - staticcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - whitespace
