name: build

on:
  push:
    branches:
    tags:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: build and test
      run: go test -race -timeout=60s -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...
    - name: install golangci-lint and goveralls
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.50.1
    - name: run linters
      run: $GITHUB_WORKSPACE/golangci-lint run ./... ;

    - name: build docker image
      run: docker-compose build
